### ISSUE TITLE
Error on M3 CPU: `bad CPU type in executable: roc-vad`

### ISSUE THREAD

**Issue by shermozle** [roc-streaming/roc-vad#1]
Installing using the binaries seems successful and after rebooting and running
`roc-vad info`

I get the message:
`zsh: bad CPU type in executable: roc-vad`

System details:
![image](https://github.com/user-attachments/assets/5747ce53-f2ad-40a6-b5af-312ec23cdff6)

I'd prefer not to have to compile but let me know if this isn't a quick fix. Happy to test reinstalling and trying again.

Note the uninstall instructions also don't work for the same reason:
`sudo: unable to execute /usr/local/bin/roc-vad: Bad CPU type in executable`

**Comment by allquixotic** [comment]
I would surmise this is because the executable is built for x86-64. Compiling from the latest source is definitely the way to go with this experimental project. It isn't very difficult.

**Comment by gavv** [comment]
Those binaries were supposed to be universal binaries, and last time I tested them, they worked on Intel and M1. Never tested on M3, though. I'll take a look.

**Comment by gavv** [comment]
Thanks for report, that was a regression with a simple fix: e7f0ff293da68fa1aa0978da826c04139bdb0c16. I've also added a check during build that produced binaries are universal.

Tagged a new release: https://github.com/roc-streaming/roc-vad/releases/tag/v0.0.3, should work now.

Feel free to reopen if the issue persist.
